# Changes here will be overwritten by Copier
_commit: v0.1.6
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage Journal utilities
distribution_name: swh-journal
have_cli: false
have_workers: false
package_root: swh/journal
project_name: swh.journal
python_minimal_version: '3.7'
readme_format: rst
